[storage]
driver = "overlay"
runroot = "/run/user/1000/containers"
graphroot = "/home/agent/.local/share/containers/storage"
rootless_storage_path = "/home/agent/.local/share/containers/storage"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
